from models.ModelConfig import ModelConfig

MODEL_CONFIGURATIONS = [
    ModelConfig(
        model='models/realistic',
        display_name='Realistic',
        use_32bit=False,
        inference_step_min=1,
        inference_step_max=100,
        inference_step_default=30,
        guidance_scale_min=0.0,
        guidance_scale_max=6.0,
        guidance_scale_default=3.2,
        resolutions=[(512,512),(512,768),(768,768),(768,1024)],
        resolutions_default_index=3,
        url='https://civitai.com/models/4201/realistic-vision-v60-b1',
        prompt_tip='(8k, RAW photo, best quality, masterpiece:1.3), (realistic, photo-realistic:1.4), (extremely detailed 8k wallpaper), {SUBJECT}',
        negative_prompt_tip='(deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers:1.4), (deformed, distorted, disfigured:1.3), poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, amputation, UnrealisticDream',
    ),
    ModelConfig(
        model='models/realism-yogi-pony',
        display_name='Realism By Yogi (Pony)',
        use_32bit=False,
        inference_step_min=1,
        inference_step_max=100,
        inference_step_default=30,
        guidance_scale_min=0.0,
        guidance_scale_max=6.0,
        guidance_scale_default=3.2,
        resolutions=[(512,512),(512,768),(768,768),(768,1024)],
        resolutions_default_index=3,
        url='https://civitai.com/models/166609/realism-by-stable-yogi',
        prompt_tip='score_9, score_8_up, score_7_up, BREAK, {SUBJECT}',
        negative_prompt_tip='score_4, score_5, score_6',
    ),
    ModelConfig(
        model='models/anireijl',
        display_name='Anireijl (Anime)',
        use_32bit=False,
        inference_step_min=20,
        inference_step_max=100,
        inference_step_default=35,
        guidance_scale_min=1.0,
        guidance_scale_max=8.0,
        guidance_scale_default=3.2,
        url='https://civitai.com/models/1478445/anireijl',
        resolutions=[(512,512),(512,768),(768,768),(768,1024)],
        resolutions_default_index=3,
        prompt_tip='best quality, ultra-detailed, highly_aesthetic, 8K, UHD, {SUBJECT}',
        negative_prompt_tip='extra_fingers, malformed_hands, deformed_feet,',
    ),
    ModelConfig(
        model='models/illustrious-realism',
        display_name='Illustrious Realism',
        use_32bit=False,
        inference_step_min=20,
        inference_step_max=35,
        inference_step_default=20,
        guidance_scale_min=3.0,
        guidance_scale_max=6.5,
        guidance_scale_default=4.0,
        resolutions=[(832,1216),(1536,2048)],
        resolutions_default_index=0,
        url='https://civitai.com/models/1412827/illustrious-realism-by-klaabu',
        prompt_tip='masterpiece, best quality, ultra-detailed, realistic skin, intricate details, highres, {SUBJECT}',
        negative_prompt_tip='low quality, worst quality, blurry, (deformed:1.3), extra fingers, cartoon, 3d, anime, bad anatomy',
    ),
    ModelConfig(
        model='models/power-puff',
        display_name='Power Puff',
        use_32bit=False,
        inference_step_min=15,
        inference_step_max=35,
        inference_step_default=20,
        guidance_scale_min=2.0,
        guidance_scale_max=10.0,
        guidance_scale_default=5.0,
        resolutions=[(832,1216),(1536,2048)],
        resolutions_default_index=0,
        url='https://civitai.com/models/805817/powerpuffmix',
    ),
    ModelConfig(
        model='models/cyber-realistic',
        display_name='CyberRealistic',
        use_32bit=False,
        inference_step_min=30,
        inference_step_max=100,
        inference_step_default=45,
        guidance_scale_min=4.0,
        guidance_scale_max=8.0,
        guidance_scale_default=7.0,
        resolutions=[(896,1152),(832,1216)],
        resolutions_default_index=0,
        url='https://civitai.com/models/15003?modelVersionId=1460987',
        negative_prompt_tip='lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry',
        prompt_tip='score_9, score_8_up, score_7_up, {SUBJECT}, ',
    ),
    ModelConfig(
        model='models/cyber-realistic-xl',
        display_name='CyberRealistic XL',
        use_32bit=False,
        inference_step_min=30,
        inference_step_max=100,
        inference_step_default=45,
        guidance_scale_min=4.0,
        guidance_scale_max=8.0,
        guidance_scale_default=7.0,
        resolutions=[(896,1152),(832,1216)],
        resolutions_default_index=0,
        url='https://civitai.com/models/312530/cyberrealistic-xl',
        negative_prompt_tip='(worst quality, low quality, normal quality, lowres, low details, oversaturated, undersaturated, overexposed, underexposed, grayscale, bad photo, bad photography, bad art:1.4)',
        prompt_tip='score_9, score_8_up, score_7_up, {SUBJECT}, ',
    ),
    ModelConfig(
        model='models/cyber-realistic-pony',
        display_name='CyberRealistic Pony',
        use_32bit=False,
        inference_step_min=30,
        inference_step_max=100,
        inference_step_default=45,
        guidance_scale_min=1.0,
        guidance_scale_max=8.0,
        guidance_scale_default=7.0,
        resolutions=[(896,1152),(832,1216)],
        resolutions_default_index=0,
        url='https://civitai.com/models/443821/cyberrealistic-pony',
        prompt_tip='score_9, score_8_up, score_7_up, {SUBJECT}, ',
        negative_prompt_tip='score_6, score_5, score_4, simplified, abstract, unrealistic, impressionistic, low resolution, lowres, bad anatomy, bad hands, missing fingers, worst quality, low quality, normal quality, cartoon, anime, drawing, sketch, illustration, artificial, poor quality',
    ),
    ModelConfig(
        model='models/reijality',
        display_name='Reijality v10',
        use_32bit=False,
        inference_step_min=20,
        inference_step_max=60,
        inference_step_default=30,
        guidance_scale_min=2.0,
        guidance_scale_max=10.0,
        guidance_scale_default=6.0,
        resolutions=[(512,512),(512,768),(768,512)],
        resolutions_default_index=2,
        prompt_tip='((best quality)), ((masterpiece)), (detailed), {SUBJECT}',
        negative_prompt_tip='extra_fingers, malformed_hands, deformed_feet,',
        url='https://civitai.com/models/1409408/reijality',
    ),
    ModelConfig(
        model='models/revanimated-v2',
        display_name='RevAnimated V2 (Anime)',
        use_32bit=False,
        inference_step_min=20,
        inference_step_max=60,
        inference_step_default=30,
        guidance_scale_min=2.0,
        guidance_scale_max=10.0,
        guidance_scale_default=6.0,
        resolutions=[(896,1152),(512,512),(512,768),(768,512),(768,768),(1024,1024)],
        resolutions_default_index=0,
        prompt_tip='best_quality, absurdres, ultra-detailed, highly_aesthetic, 8K, UHD, highly_detailed_eyes, depth_of_field, subject_focus, {SUBJECT}',
        negative_prompt_tip='extra_fingers, malformed_hands, deformed_feet,',
        url='https://civitai.com/models/7371/rev-animated',
    ),
]